version: "3"
services:
  jenkins:
    image: jenkins:alpine
    volumes:
      - /data/jenkins:/var/jenkins_home:rw
    networks:
      - haproxy
    ports:
      - "8080:8080"
      - "50000:50000"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == swarm-master1]
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
    user: root

networks:
  haproxy:
    external:
      name: haproxy_haproxy
