version: '3'
services:
  nettools:
    image: reg.xiaoneng.cn/library/nettools
    command: top
    networks:
      - overlay_test
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 512M

networks:
  overlay_test:
    driver: overlay
      
