version: "3.0"
services:
  influxdb:
      image: influxdb
      network_mode: "host"
      ports:
      - 8086:8086
      - 2003:2003
      volumes:
        - ./influxdb:/var/lib/influxdb
        - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      environment:
        - INFLUXDB_GRAPHITE_ENABLED=true
  
  chronograf:
      image: chronograf
      network_mode: "host"
      ports:
        - 8888:8888
      volumes:
        - ./chronograf:/var/lib/chronograf
      command: chronograf --influxdb-url=http://localhost:8086
  
  kapacitor:
      image: kapacitor
      network_mode: "host"
      ports:
        - 9092:9092
      volumes:
        - ./kapacitor:/var/lib/kapacitor
        - ./kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
        
  telegraf:
      image: telegraf
      network_mode: "host"
      volumes:
        - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf

