version: "3.3"
services:
  visualizer:
    image: dockersamples/visualizer:stable
    networks:
      - haproxy
    environment:
      - SERVICE_PORTS=8080
      - VIRTUAL_HOST=visualizer.xiaoneng.cn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
          constraints: [node.hostname == swarm-master1]
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3

networks:
  haproxy:
    external:
      name: haproxy_haproxy
